from __future__ import annotations

STAT_SOURCE_MAP: dict[str, dict[str, object]] = {
    "kills": {
        "preferred_source": "existing",
        "fallback_source": None,
        "source_field_name": None,
        "coverage_status": "filled_existing",
        "candidate_fields": [],
    },
    "deaths": {
        "preferred_source": "existing",
        "fallback_source": None,
        "source_field_name": None,
        "coverage_status": "filled_existing",
        "candidate_fields": [],
    },
    "creep_score": {
        "preferred_source": "existing",
        "fallback_source": None,
        "source_field_name": None,
        "coverage_status": "filled_existing",
        "candidate_fields": [],
    },
    "gpm": {
        "preferred_source": "existing",
        "fallback_source": None,
        "source_field_name": None,
        "coverage_status": "filled_existing",
        "candidate_fields": [],
    },
    "teamfight_participation": {
        "preferred_source": "existing",
        "fallback_source": None,
        "source_field_name": None,
        "coverage_status": "filled_existing",
        "candidate_fields": [],
    },
    "first_blood": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "firstblood_claimed",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["firstblood_claimed", "first_blood_claimed", "firstblood_claim"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "stuns": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "stuns",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["stuns"],
        "min_allowed_raw": 0.0,
        "expects_integer": False,
    },
    "runes_grabbed": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "rune_pickups",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["rune_pickups", "runes_grabbed", "runes"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "wards_placed": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "obs_placed",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["obs_placed", "observer_wards_placed", "wards_placed"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "smokes_used": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "item_uses.smoke_of_deceit",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["used_smoke_of_deceit", "smokes_used", "item_uses.smoke_of_deceit", "item_usage.smoke_of_deceit"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "camps_stacked": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "camps_stacked",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["camps_stacked"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "courier_kills": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "courier_kills",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["courier_kills", "couriers_killed"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "roshan_kills": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "roshans_killed",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["roshans_killed", "roshan_kills"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "watchers_taken": {
        "preferred_source": "stratz",
        "fallback_source": "opendota",
        "source_field_name": "watchers_taken",
        "coverage_status": "source_needed",
        "candidate_fields": ["watchers_taken"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "lotus": {
        "preferred_source": "stratz",
        "fallback_source": "opendota",
        "source_field_name": "lotus_units",
        "coverage_status": "source_needed",
        "candidate_fields": ["lotus_units", "lotus"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
    "tormentor_kills": {
        "preferred_source": "opendota",
        "fallback_source": "stratz",
        "source_field_name": "objectives.CHAT_MESSAGE_MINIBOSS_KILL",
        "coverage_status": "backfill_planned",
        "candidate_fields": ["objectives.CHAT_MESSAGE_MINIBOSS_KILL"],
        "min_allowed_raw": 0.0,
        "expects_integer": True,
    },
}

STAT_POINT_FORMULAS: dict[str, object] = {
    "kills": 107.0,
    "deaths": ("deaths_special", None),
    "creep_score": 3.0,
    "gpm": 2.0,
    "camps_stacked": 234.0,
    "runes_grabbed": 141.0,
    "wards_placed": 117.0,
    "watchers_taken": 147.0,
    "lotus": 176.0,
    "roshan_kills": 1172.0,
    "teamfight_participation": ("teamfight_special", None),
    "stuns": 10.0,
    "tormentor_kills": 879.0,
    "courier_kills": 703.0,
    "first_blood": ("binary_bonus", 1934.0),
    "smokes_used": 293.0,
}
